In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("task.csv")

In [5]:
df

      Name  Age  Hours_Studied  Marks
0     Hari   23              2     66
1   Aayush   20              5     69
2   Aayush   18              6     78
3   Bikash   21              6     99
4      Ram   18              3     98
..     ...  ...            ...    ...
95    Rita   24              6     88
96     Ram   19              2     57
97    Rita   22              7     81
98    Rita   23              1    100
99    Rita   20              2     67

[100 rows x 4 columns]

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           100 non-null    str
 1   Age            100 non-null    int64
 2   Hours_Studied  100 non-null    int64
 3   Marks          100 non-null    int64
dtypes: int64(3), str(1)
memory usage: 3.3 KB

In [11]:
df.shape

(100, 4)

In [12]:
df.describe()

              Age  Hours_Studied      Marks
count  100.000000     100.000000  100.00000
mean    20.720000       4.600000   80.06000
std      1.985198       2.522625   14.26433
min     18.000000       1.000000   52.00000
25%     19.000000       2.000000   67.75000
50%     21.000000       5.000000   81.00000
75%     22.000000       7.000000   93.00000
max     24.000000       8.000000  100.00000